apiVersion: v1
kind: Pod
metadata:
  name: customscript
spec:
  restartPolicy: OnFailure
  containers:
  - name: customscript
    image: sdough.azurecr.io/customscript:latest
    command: [ "/bin/bash", "-c" ]
    args:
      - echo starting;
        /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.1.13/bin/custom-script-shim install;
        /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.1.13/bin/custom-script-shim enable;
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.1.13/status/
      name: cse
      subPath: status
    - mountPath: /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.1.13/config/
      name: cse
      subPath: config
    - mountPath: /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.1.13/HandlerEnvironment.json
      name: cse
      subPath: HandlerEnvironment.json
    - mountPath: /host
      name: host
  volumes:
  - name: cse
    hostPath:
      path: /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.1.13/
      type: Directory
  - name: host
    hostPath:
      path: /
      type: Directory